version: 2.1

parameters:
  deploy-update:
    type: string
    default: deploy
  image-name:
    type: string
    default: ventas
  service-name:
    type: string
    default: ventas-site

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202010-01
  docker-publisher:
    docker:
      - image: cimg/base:2021.04

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker Image
          command: |
            docker build --tag ${DOCKERHUB_USERNAME}/<< pipeline.parameters.image-name >>:${CIRCLE_SHA1} --build-arg API_CONFIGURADOR_URL=${API_CONFIGURADOR_URL} --build-arg API_VENTAS_URL=${API_VENTAS_URL} .
      - run:
          name: Archive Docker Image
          command: docker save --output image.tar "${DOCKERHUB_USERNAME}/<< pipeline.parameters.image-name >>:${CIRCLE_SHA1}"
      - persist_to_workspace:
          root: .
          paths:
            - "./image.tar"
  push:
    executor: docker-publisher
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load Docker Image
          command: docker load --input /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image
          command: |
            echo "${DOCKERHUB_PASS}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin \
            docker push "${DOCKERHUB_USERNAME}/<< pipeline.parameters.image-name >>:${CIRCLE_SHA1}"

  deploy:
    executor: machine-executor
    steps:
      - add_ssh_keys
      - when:
          condition:
            equal: [deploy, << pipeline.parameters.deploy-update >>]
          steps:
            - run:
                name: Deploy Over SSH
                command: |
                  ssh $SSH_USER@$SSH_HOST_FRONTEND "docker service create --name << pipeline.parameters.service-name >> \
                  --replicas 2 \
                  --publish ${PORT}:3000 \
                  --update-order start-first \
                  --rollback-order start-first"
      - when:
          condition:
            equal: [update, << pipeline.parameters.deploy-update >>]
          steps:
            - run: 
                name: Update Deployment
                command: |
                  ssh $USER_USER@$SSH_HOST_FRONTEND "docker service update \
                  --image ${DOCKERHUB_USERNAME}/<< pipeline.parameters.image-name >>:${CIRCLE_SHA1} \
                  << pipeline.parameters.service-name >>"

workflows:
  version: 2
  build-push-deploy:
    jobs:
      - build:
          context: greencompany
          filters:
            branches:
              only: Desarrollo_productivo
      - push:
          context: greencompany
          requires:
            - build
      - deploy:
          context: greencompany
          requires:
            - push

